Jsign fix optional
gballet/zig-rlp pull request #25
Opened 2024-04-15 20:40 UTC by jsign

**Note: Merge #22 first.**

This PR fixes a bug when deserializing optional fields.

2024-04-15 20:42 UTC, jsign commented on src/deserialize.zig
> -                return serialized.len;
This line was incorrect. `serialized` is the full remaining bytes to process, not only the bytes scoped to the optional. 

This was found by trying to deserialize a tx sent to the zero address for creating a contract.

2024-04-24 12:16 UTC, gballet requested changes
I think there was some branch issue, but the fix itself LGTM

2024-04-24 12:16 UTC, gballet commented on src/main.zig
this looks like a merge error? I don't see the connection between optionals and `GenericRLPValue`?

2024-04-24 12:28 UTC, jsign commented on src/main.zig
As mentioned in the PR description:
> Note: Merge https://github.com/gballet/zig-rlp/pull/22 first.

2024-04-24 12:30 UTC, jsign commented on src/main.zig
The reason is stacked on top, is that for [phant ](https://github.com/jsign/phant/pull/30) I need all the fixes in to make progress.

2024-04-25 18:46 UTC, gballet approved these changes
LGTM

2024-04-25 18:46 UTC, merged